# Generated by Django 4.1.6 on 2023-02-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='relation',
            field=models.CharField(default='Self', max_length=50),
        ),
    ]
