# Generated by Django 4.1.6 on 2023-02-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_gender_alter_user_maritial_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('talak', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=40)),
                ('pincode', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
