# Generated by Django 4.1.6 on 2023-02-16 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.CharField(default='None', max_length=1000)),
                ('village_address', models.CharField(default='None', max_length=1000)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.village')),
            ],
        ),
        migrations.CreateModel(
            name='OccupationAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_address', models.CharField(default='None', max_length=1000)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.family')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='related_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.family'),
        ),
    ]
