# Generated by Django 4.1.6 on 2023-02-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='no_of_families',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
