# Generated by Django 4.1.6 on 2023-02-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_event_village_shakha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='about',
            field=models.TextField(max_length=255),
        ),
    ]
