# Generated by Django 4.1.6 on 2023-02-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_event_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='in_laws_village',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
