# Generated by Django 4.1.6 on 2023-03-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_user_in_laws_village"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("details", models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Founder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("city", models.CharField(max_length=80)),
                ("about", models.TextField(max_length=1000)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="founders/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocietyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("city", models.CharField(max_length=80)),
            ],
        ),
    ]
