# Generated by Django 4.1.6 on 2023-07-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_content_founder_societymember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="details",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="content",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="about",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="founder",
            name="about",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="founder",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="societymember",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
