# Generated by Django 4.1.6 on 2023-08-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_content_details_alter_content_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitteeMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("position", models.CharField(default="Member", max_length=80)),
                ("detail", models.TextField(default="Current Committee Member")),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="committee-members/"
                    ),
                ),
            ],
        ),
    ]
