# Generated by Django 4.1.6 on 2023-08-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_committeemember"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="in_laws_shakha",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="shakha",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
