# Generated by Django 4.1.6 on 2023-09-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_job",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="in_laws_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
