# Generated by Django 4.1.6 on 2024-02-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_blog_is_job_user_in_laws_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="additional_phone",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="email_id",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
